test_that("Model run (no intervention) tests", {
  s1<-Set_up()
  r1<-Single_run(tt=seq(0,10,0.1), params=s1[[1]], states=s1[[2]])
  expect_is(r1, 'deSolve')
  expect_is(r1[,1], 'numeric')
  expect_error(Single_run())
  s1<-Set_up()
  m1<-Run_model(Time=10)
  expect_is(m1, 'data.frame') 
  expect_is(m1[,1], 'numeric')
  expect_error(Run_model(), 'argument "Time" is missing')
  m2<-Run_model(Time=10, Params=s1[[1]], Initial_states=s1[[2]])
  expect_is(m2, 'data.frame') 
  expect_is(m2[,1], 'numeric')
})