test_that("Model run (no intervention) tests", {
  s1 <- set_up()
  r1 <- single_run(tt = seq(0, 10, 0.1), params = s1[[1]], states = s1[[2]])
  expect_is(r1, "deSolve")
  expect_is(r1[, 1], "numeric")
  expect_error(single_run())
  s1 <- set_up()
  m1 <- run_model(time = 10)
  expect_is(m1, "data.frame")
  expect_is(m1[, 1], "numeric")
  expect_error(run_model(), 'argument "time" is missing')
  m2 <- run_model(time = 10, params = s1[[1]], initial_states = s1[[2]])
  expect_is(m2, "data.frame")
  expect_is(m2[, 1], "numeric")
})
