## Automatically generated by odin 1.3.1 - do not edit
cyst_generator_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "cyst_generator_rhs_dde",
      rhs_desolve = "cyst_generator_rhs_desolve",
      initmod_desolve = "cyst_generator_initmod_desolve",
      output_dde = "cyst_generator_output_dde"),
    dll = "epicyst",
    user = c("age_rate_human", "age_rate_pig", "alpha", "bH", "CCC0", "chi",
             "CTC0", "dE", "delta", "dH", "dP", "dPslg", "E0", "epsilon",
             "eta", "HPS", "IH0", "IHC0", "IPH0", "IPL0", "na_human",
             "na_pig", "phi", "pih", "pil", "PP0", "PPS", "psi", "RP0",
             "RR_cysticercosis", "SH0", "SHC0", "slgage_foi", "slgtage",
             "slgtage_bfr", "SP0", "tau", "theta", "VP0"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("cyst_generator_rhs_dde", package = "epicyst")
        .C("cyst_generator_rhs_desolve", package = "epicyst")
        .C("cyst_generator_initmod_desolve", package = "epicyst")
        .C("cyst_generator_output_dde", package = "epicyst")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("cyst_generator_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "epicyst")
    },

    update_metadata = function() {
      meta <- .Call("cyst_generator_metadata", private$ptr,
                    PACKAGE = "epicyst")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("cyst_generator_create", user, PACKAGE = "epicyst")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/cyst_generator.json", mustWork = TRUE,
                             package = "epicyst")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("cyst_generator_set_user", private$ptr, user, PACKAGE = "epicyst")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("cyst_generator_initial_conditions", private$ptr, t, PACKAGE = "epicyst")
    },

    rhs = function(t, y) {
      .Call("cyst_generator_rhs_r", private$ptr, t, y, PACKAGE = "epicyst")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("cyst_generator_contents", private$ptr, PACKAGE = "epicyst")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_ode(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


cyst_generator <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("cyst_generator")
  cyst_generator_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(cyst_generator) <- "odin_generator"
attr(cyst_generator, "generator") <- cyst_generator_
