## This file was automatically generated by odin.
## Do not edit by hand as changes will be lost.
.R6_cyst_generator <- R6::R6Class(
  "odin_model",
  parent_env = environment(odin::odin),
  public = list(
    name = "cyst_generator",
    ptr = NULL,
    use_dde = NULL,
    ## Cache:
    init = NULL,
    variable_order = NULL,
    names = NULL,
    transform_variables = NULL,
    ## Methods:
    initialize = function(user = NULL, use_dde = FALSE) {
      self$ptr <- .Call("cyst_generator_create", user, use_dde, PACKAGE = "deCyst")
      self$use_dde <- use_dde
      self$init <- .Call("cyst_generator_initialise", self$ptr, NA_real_, PACKAGE = "deCyst")
      if (use_dde) {
        loadNamespace("dde")
      }
      self$update_cache()
    },

    set_user = function(..., user = list(...)) {
      .Call("r_cyst_generator_set_user", self$ptr, user, PACKAGE = "deCyst")
      self$init <- .Call("cyst_generator_initialise", self$ptr, NA_real_, PACKAGE = "deCyst")
      invisible(self$init)
    },

    update_cache = function() {
      self$variable_order <- .Call("cyst_generator_variable_order", self$ptr, PACKAGE = "deCyst")
      odin_prepare(self, FALSE)
    },

    deriv = function(t, y) {
      .Call("cyst_generator_deriv_r", self$ptr, t, y, PACKAGE = "deCyst")
    },

    initial = function(t) {
      self$init
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      if (is.null(y)) {
        y <- self$init
      }
      if (self$use_dde) {
        ret <- dde::dopri(y, t, "cyst_generator_deriv_dde", self$ptr,
                          dllname="deCyst",
                          parms_are_real=FALSE,
                          by_column=TRUE, return_initial=TRUE,
                          return_time=TRUE, return_output_with_y=TRUE, ...)
      } else {
        ret <- deSolve::ode(y, t, "cyst_generator_deriv_ds", self$ptr,
                            initfunc = "cyst_generator_initmod_ds", dllname = "deCyst",
                            ...)
      }
      if (use_names) {
        colnames(ret) <- self$names
      } else {
        colnames(ret) <- NULL
      }
      ret
    },

    contents = function() {
      .Call("cyst_generator_contents", self$ptr, PACKAGE = "deCyst")
    }
  ))
cyst_generator <- function(E0, IP0, SP0, tau, SHC0, IHC0, SH0, IH0, LEH, LEP, HPS, PPS, dH, dP, AEL, dE, delta, TPrev, CPrev, PTPrev, phi, ATL, ADI, alpha, eta, pil, chil, pih, chih, epsilon = NULL, user = list(E0 = E0, IP0 = IP0, SP0 = SP0, tau = tau, SHC0 = SHC0, IHC0 = IHC0, SH0 = SH0, IH0 = IH0, LEH = LEH, LEP = LEP, HPS = HPS, PPS = PPS, dH = dH, dP = dP, AEL = AEL, dE = dE, delta = delta, TPrev = TPrev, CPrev = CPrev, PTPrev = PTPrev, phi = phi, ATL = ATL, ADI = ADI, alpha = alpha, eta = eta, pil = pil, chil = chil, pih = pih, chih = chih, epsilon = epsilon), use_dde = FALSE) {
  .R6_cyst_generator$new(user = user, use_dde = use_dde)
}
